# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-19 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_geoip', '0001_initial'),
        ('client', '0002_auto_20160714_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': '\u041a\u043b\u0438\u0435\u043d\u0442', 'verbose_name_plural': '\u041a\u043b\u0438\u0435\u043d\u0442\u044b'},
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field=b'region', chained_model_field=b'region', null=True, on_delete=django.db.models.deletion.CASCADE, to='django_geoip.City', verbose_name='\u0413\u043e\u0440\u043e\u0434'),
        ),
        migrations.AddField(
            model_name='client',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_geoip.Country', verbose_name='\u0421\u0442\u0440\u0430\u043d\u0430'),
        ),
        migrations.AddField(
            model_name='client',
            name='region',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field=b'country', chained_model_field=b'country', null=True, on_delete=django.db.models.deletion.CASCADE, to='django_geoip.Region', verbose_name='\u0420\u0435\u0433\u0438\u043e\u043d'),
        ),
    ]
