# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 14:38
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='index',
            options={'verbose_name': '\u0413\u043b\u0430\u0432\u043d\u0430\u044f \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0430', 'verbose_name_plural': '\u0413\u043b\u0430\u0432\u043d\u0430\u044f \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0430'},
        ),
        migrations.AddField(
            model_name='index',
            name='seo',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='\u0421\u0415\u041e \u0442\u0435\u043a\u0441\u0442 \u0433\u043b\u0430\u0432\u043d\u043e\u0439 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0438'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banner',
            name='head',
            field=ckeditor.fields.RichTextField(help_text='\u0420\u0435\u0434\u0430\u043a\u0442\u0438\u0440\u0443\u0435\u043c\u044b\u0439 \u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u0430\u043d\u043d\u0435\u0440\u0430', verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
    ]
