# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 14:57
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20160405_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, '\u041e \u043c\u0430\u0433\u0430\u0437\u0438\u043d\u0435'), (2, '\u041f\u0440\u043e\u0438\u0437\u0432\u043e\u0434\u0438\u0442\u0435\u043b\u0438'), (3, '\u041e\u043f\u043b\u0430\u0442\u0430'), (4, '\u0414\u043e\u0441\u0442\u0430\u0432\u043a\u0430'), (5, '\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u044b')], verbose_name='\u0422\u0438\u043f \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0438')),
                ('text', ckeditor.fields.RichTextField(help_text='\u0442\u0435\u043a\u0441\u0442 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0438', verbose_name='\u0422\u0435\u043a\u0441\u0442')),
            ],
            options={
                'verbose_name': '\u0421\u0442\u0430\u0442\u0438\u0447\u0435\u0441\u043a\u0430\u044f \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0430',
                'verbose_name_plural': '\u0421\u0442\u0430\u0442\u0438\u0447\u0435\u0441\u043a\u0430\u044f \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0430',
            },
        ),
    ]
