# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 12:08
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20160412_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', ckeditor.fields.RichTextField(help_text='\u0418\u043c\u044f \u0431\u0440\u0435\u043d\u0434\u0430', verbose_name='\u0418\u043c\u044f \u0431\u0440\u0435\u043d\u0434\u0430')),
                ('img', sorl.thumbnail.fields.ImageField(help_text='\u041b\u043e\u0433\u043e\u0442\u0438\u043f \u0431\u0440\u0435\u043d\u0434\u0430', upload_to='brand/uploads', verbose_name='\u041b\u043e\u0433\u043e\u0442\u0438\u043f \u0431\u0440\u0435\u043d\u0434\u0430')),
                ('text', ckeditor.fields.RichTextField(help_text='\u0420\u0435\u0434\u0430\u043a\u0442\u0438\u0440\u0443\u0435\u043c\u044b\u0439 \u0442\u0435\u043a\u0441\u0442 \u0431\u0440\u0435\u043d\u0434\u0430', verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0431\u0440\u0435\u043d\u0434\u0430')),
            ],
            options={
                'verbose_name': '\u041f\u0440\u043e\u0438\u0437\u0432\u043e\u0434\u0438\u0442\u0435\u043b\u044c',
                'verbose_name_plural': '\u041f\u0440\u043e\u0438\u0437\u0432\u043e\u0434\u0438\u0442\u0435\u043b\u0438',
            },
        ),
        migrations.AlterField(
            model_name='page',
            name='type',
            field=models.IntegerField(choices=[(1, '\u041e \u043c\u0430\u0433\u0430\u0437\u0438\u043d\u0435'), (2, '\u041e\u043f\u043b\u0430\u0442\u0430'), (3, '\u0414\u043e\u0441\u0442\u0430\u0432\u043a\u0430'), (4, '\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u044b')], unique=True, verbose_name='\u0422\u0438\u043f \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0438'),
        ),
    ]
