# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20160412_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(help_text='\u0418\u043c\u044f \u0431\u0440\u0435\u043d\u0434\u0430', max_length=100, verbose_name='\u0418\u043c\u044f \u0431\u0440\u0435\u043d\u0434\u0430'),
        ),
    ]
