# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 20:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20160412_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='index',
        ),
    ]
