# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20160420_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='type',
            field=models.IntegerField(choices=[(1, '\u0413\u0430\u0440\u0430\u043d\u0442\u0438\u044f \u0438 \u0441\u0435\u0440\u0432\u0438\u0441'), (2, '\u041e\u043f\u043b\u0430\u0442\u0430 \u0438 \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0430'), (3, '\u0414\u0438\u0441\u043a\u043e\u043d\u0442\u043d\u0430\u044f \u043f\u0440\u043e\u0433\u0440\u0430\u043c\u043c\u0430'), (4, '\u0421\u043e\u0442\u0440\u0443\u0434\u043d\u0438\u0447\u0435\u0441\u0442\u0432\u043e'), (5, '\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u044b')], unique=True, verbose_name='\u0422\u0438\u043f \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0438'),
        ),
    ]
