# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 10:53
from __future__ import unicode_literals

import catalog.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mptt.fields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to=catalog.models.image_path, verbose_name='\u0424\u043e\u0442\u043e')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='\u0427\u041f\u0423')),
                ('description', models.TextField(blank=True, null=True, verbose_name='\u0421\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u0435 \u043e \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438')),
                ('options', models.BooleanField(default=False, verbose_name='\u0422\u043e\u0432\u0430\u0440 \u0438\u043c\u0435\u0435\u0442 \u0431\u043e\u043b\u044c\u0448\u0435 1-\u0433\u043e \u0430\u0440\u0442\u0438\u043a\u0443\u043ba')),
                ('order', models.PositiveIntegerField(default=0)),
                ('category_img', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='category_img', verbose_name='\u0424\u043e\u043d \u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.Category', verbose_name='\u043a\u0430\u0442\u0430\u043b\u043e\u0433-\u0440\u043e\u0434\u0438\u0442\u0435\u043b\u044c')),
            ],
            options={
                'verbose_name': '\u043a\u0430\u0442\u0430\u043b\u043e\u0433',
                'verbose_name_plural': '\u043a\u0430\u0442\u0430\u043b\u043e\u0433\u0438',
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='FileProcessing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileprocessing', models.FileField(upload_to=catalog.models.image_path, verbose_name='\u0424\u0430\u0439\u043b')),
            ],
            options={
                'verbose_name': '\u0418\u043c\u043f\u043e\u0440\u0442',
                'verbose_name_plural': '\u0418\u043c\u043f\u043e\u0440\u0442',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u0410\u0440\u0442\u0438\u043a\u0443\u043b')),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=catalog.models.image_path, verbose_name='\u0424\u043e\u0442\u043e')),
                ('description', models.TextField(blank=True, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('special_offer', models.BooleanField(default=False, verbose_name='\u0421\u043f\u0435\u0446\u0438\u0430\u043b\u044c\u043d\u043e\u0435 \u043f\u0440\u0435\u0434\u043b\u043e\u0436\u0435\u043d\u0438\u0435')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Category', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f')),
            ],
            options={
                'verbose_name': '\u0422\u043e\u0432\u0430\u0440',
                'verbose_name_plural': '\u0422\u043e\u0432\u0430\u0440\u044b',
            },
        ),
        migrations.CreateModel(
            name='GoodsVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u0410\u0440\u0442\u0438\u043a\u0443\u043b')),
                ('size', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='\u0420\u0430\u0437\u043c\u0435\u0440')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='\u0412\u0435\u0441')),
                ('price_gramm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='\u0426\u0435\u043d\u0430 \u0437\u0430 \u0433\u0440\u0430\u043c\u043c')),
                ('price_product', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='\u0426\u0435\u043d\u0430 \u0437\u0430 \u0438\u0437\u0434.')),
                ('warehouse', models.IntegerField(default=0, verbose_name='\u0421\u043a\u043b\u0430\u0434')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='catalog.Goods', verbose_name='\u0422\u043e\u0432\u0430\u0440')),
            ],
            options={
                'ordering': ('article',),
                'verbose_name': '\u0412\u0430\u0440\u0438\u0430\u043d\u0442',
                'verbose_name_plural': '\u0412\u0430\u0440\u0438\u0430\u043d\u0442\u044b',
            },
        ),
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u0421\u043f\u0435\u0446\u0438\u0430\u043b\u044c\u043d\u043e\u0435 \u043f\u0440\u0435\u0434\u043b\u043e\u0436\u0435\u043d\u0438\u0435',
                'verbose_name_plural': '\u0421\u043f\u0435\u0446\u0438\u0430\u043b\u044c\u043d\u044b\u0435 \u043f\u0440\u0435\u0434\u043b\u043e\u0436\u0435\u043d\u0438\u044f',
            },
        ),
    ]
