# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20160412_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_img',
        ),
        migrations.RemoveField(
            model_name='category',
            name='options',
        ),
        migrations.RemoveField(
            model_name='category',
            name='order',
        ),
        migrations.AddField(
            model_name='category',
            name='activate',
            field=models.BooleanField(default=1212, verbose_name='\u0410\u043a\u0442\u0438\u0432\u0430\u0446\u0438\u044f \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438'),
            preserve_default=False,
        ),
    ]
