# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20160420_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='options',
            field=models.BooleanField(default=False, verbose_name='\u0422\u043e\u0432\u0430\u0440 \u0438\u043c\u0435\u0435\u0442 \u0431\u043e\u043b\u044c\u0448\u0435 1-\u0433\u043e \u0430\u0440\u0442\u0438\u043a\u0443\u043ba'),
        ),
    ]
