# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 12:26
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_category_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, choices=[(0, '\u0423\u043a\u0440\u0430\u0438\u043d\u0430'), (1, '\u041a\u0438\u0435\u0432'), (2, '\u0414\u043d\u0435\u043f\u0440\u043e\u043f\u0435\u0442\u0440\u043e\u0432\u0441\u043a'), (3, '\u0417\u0430\u043f\u043e\u0440\u043e\u0436\u044c\u0435')], max_length=100, null=True, verbose_name='\u041b\u043e\u043a\u0430\u0446\u0438\u044f \u0442\u043e\u0432\u0430\u0440\u0430')),
            ],
            options={
                'verbose_name': '\u041b\u043e\u043a\u0430\u0446\u0438\u044f',
                'verbose_name_plural': '\u041b\u043e\u043a\u0430\u0446\u0438\u0438',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='kod',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u041a\u043e\u0434 \u0442\u043e\u0432\u0430\u0440\u0430'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='goods',
            name='location',
            field=models.ManyToManyField(to='catalog.Location'),
        ),
    ]
