# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20160510_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(blank=True, choices=[('Ukraine', '\u0423\u043a\u0440\u0430\u0438\u043d\u0430'), ('Kiev', '\u041a\u0438\u0435\u0432'), ('Dnepropetrovsk', '\u0414\u043d\u0435\u043f\u0440\u043e\u043f\u0435\u0442\u0440\u043e\u0432\u0441\u043a'), ('Zaporoje', '\u0417\u0430\u043f\u043e\u0440\u043e\u0436\u044c\u0435')], max_length=100, null=True, unique=True, verbose_name='\u041b\u043e\u043a\u0430\u0446\u0438\u044f \u0442\u043e\u0432\u0430\u0440\u0430'),
        ),
    ]
