# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20160510_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='diskont',
            field=models.PositiveIntegerField(default=0, verbose_name='\u0421\u043a\u0438\u0434\u043a\u0430 \u0432 \u043f\u0440\u043e\u0446\u0435\u043d\u0442\u0430\u0445'),
        ),
        migrations.AddField(
            model_name='goods',
            name='garanty',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u0413\u0430\u0440\u0430\u043d\u0442\u0438\u044f \u0432 \u043c\u0435\u0441\u044f\u0446\u0430\u0445'),
        ),
        migrations.AddField(
            model_name='goods',
            name='izm',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u0417\u0430 \u0441\u043a\u043e\u043b\u044c\u043a\u043e \u0443\u043a\u0430\u0437\u0430\u043d\u0430 \u0446\u0435\u043d\u0430'),
        ),
        migrations.AddField(
            model_name='goods',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u0426\u0435\u043d\u0430 \u0432 \u0433\u0440\u043d.'),
        ),
        migrations.AddField(
            model_name='goods',
            name='stock',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u041e\u0441\u0442\u0430\u0442\u043e\u043a \u043d\u0430 \u0441\u043a\u043b\u0430\u0434\u0435'),
        ),
        migrations.AddField(
            model_name='goods',
            name='youtube_url',
            field=models.URLField(blank=True, null=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 youtube.com'),
        ),
    ]
