# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20160510_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='soput',
            field=models.ManyToManyField(help_text='\u041f\u0435\u0440\u0435\u0447\u0438\u0441\u043b\u044f\u0435\u043c \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438 \u0434\u043b\u044f \u0440\u0430\u043d\u0434\u043e\u043c\u043d\u044b\u0445 \u0442\u043e\u0432\u0430\u0440\u043e\u0432', related_name='soput', to='catalog.Category', verbose_name='\u0421\u043e\u043f\u0443\u0442\u0441\u0442\u0432\u0443\u044e\u0449\u0430\u044f \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f'),
        ),
    ]
