# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_auto_20160511_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='\u0426\u0435\u043d\u0430 \u0432 \u0433\u0440\u043d.'),
        ),
    ]
