# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 14:52
from __future__ import unicode_literals

import catalog.models
from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_auto_20160511_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=sorl.thumbnail.fields.ImageField(null=True, upload_to=catalog.models.image_path, verbose_name='\u0424\u043e\u0442\u043e'),
        ),
    ]
