# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_auto_20160511_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='soput',
        ),
        migrations.AddField(
            model_name='goods',
            name='soput',
            field=models.TextField(blank=True, help_text='\u041f\u0435\u0440\u0435\u0447\u0438\u0441\u043b\u044f\u0435\u043c \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438 \u0434\u043b\u044f \u0440\u0430\u043d\u0434\u043e\u043c\u043d\u044b\u0445 \u0442\u043e\u0432\u0430\u0440\u043e\u0432.', null=True, verbose_name='\u0421\u043e\u043f\u0443\u0442\u0441\u0442\u0432\u0443\u044e\u0449\u0438\u0435 \u0442\u043e\u0432\u0430\u0440\u044b'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(blank=True, choices=[('\u0423\u043a\u0440\u0430\u0438\u043d\u0430', '\u0423\u043a\u0440\u0430\u0438\u043d\u0430'), ('\u041a\u0438\u0435\u0432', '\u041a\u0438\u0435\u0432'), ('\u0414\u043d\u0435\u043f\u0440\u043e\u043f\u0435\u0442\u0440\u043e\u0432\u0441\u043a', '\u0414\u043d\u0435\u043f\u0440\u043e\u043f\u0435\u0442\u0440\u043e\u0432\u0441\u043a'), ('\u0417\u0430\u043f\u043e\u0440\u043e\u0436\u044c\u0435', '\u0417\u0430\u043f\u043e\u0440\u043e\u0436\u044c\u0435')], max_length=100, null=True, unique=True, verbose_name='\u041b\u043e\u043a\u0430\u0446\u0438\u044f \u0442\u043e\u0432\u0430\u0440\u0430'),
        ),
    ]
