# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 20:11
from __future__ import unicode_literals
from django.utils import timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_auto_20160511_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileprocessing',
            name='date',
            field=models.DateTimeField(auto_now=True, default=timezone.now(), verbose_name='\u0414\u0430\u0442\u0430 \u0438\u043c\u043f\u043e\u0440\u0442\u0430'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileprocessing',
            name='status',
            field=models.BooleanField(default=False, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441'),
        ),
    ]
