# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_auto_20160511_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='diskont',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='\u0421\u043a\u0438\u0434\u043a\u0430 \u0432 \u043f\u0440\u043e\u0446\u0435\u043d\u0442\u0430\u0445'),
        ),
    ]
