# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-27 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_category_menu_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='\u0426\u0435\u043d\u0430 \u0432 \u0433\u0440\u043d.'),
        ),
    ]
