# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-27 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_goods_old_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='\u0421\u0442\u0430\u0440\u0430\u044f \u0446\u0435\u043d\u0430.'),
        ),
    ]
